# IMPORTING DATASETS

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
crops_df=pd.read_csv("Crop_recommendation.csv")

In [23]:
crops_df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# DATA PREPROCESSING

In [7]:
crops_df.size

17600

In [33]:
crops_df.shape 
# 2200 rows & 8 columns

(2200, 8)

In [31]:
crops_df.isnull().sum() 
# this shows no null column is present in dataset

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [39]:
crops_df.duplicated().sum()
# no duplicate rows is present

0

In [15]:
crops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [19]:
crops_df.drop('label',axis=1).corr()

,N,P,K,temperature,humidity,ph,rainfall
N,1.000000,-0.231460,-0.140512,0.026504,0.190688,0.096683,0.059020
P,-0.231460,1.000000,0.736232,-0.127541,-0.118734,-0.138019,-0.063839
K,-0.140512,0.736232,1.000000,-0.160387,0.190859,-0.169503,-0.053461
temperature,0.026504,-0.127541,-0.160387,1.000000,0.205320,-0.017795,-0.030084
humidity,0.190688,-0.118734,0.190859,0.205320,1.000000,-0.008483,0.094423
ph,0.096683,-0.138019,-0.169503,-0.017795,-0.008483,1.000000,-0.109069
rainfall,0.059020,-0.063839,-0.053461,-0.030084,0.094423,-0.109069,1.000000

In [41]:
crops_df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [47]:
crops_df.sample(frac=0.01)

        N   P   K  temperature   humidity        ph    rainfall        label
121    99  50  15    18.147101  71.094453  5.573286   88.077537        maize
1068   93  85  49    27.967991  79.286257  5.694244  119.476556       banana
312    28  80  17    19.622078  18.671709  5.809420  144.156745  kidneybeans
1819   31   6  26    29.128591  91.309248  5.741367  157.238855      coconut
1188   22  18  31    30.764552  47.937915  5.956027   90.385035        mango
125    79  51  16    25.337977  68.498360  6.586245   96.463802        maize
2004   96  41  40    23.584193  72.004608  6.090060  190.424216         jute
977    14   8  43    21.925139  94.464853  7.051655  111.716202  pomegranate
70     61  52  41    24.976695  83.891805  6.880431  204.800185         rice
14     94  50  37    25.665852  80.663850  6.948020  209.586971         rice
805    29  71  18    22.175000  62.138738  6.410441   53.466226       lentil
2106  109  31  27    23.059519  50.406094  6.973840  164.497187       coffee
1017  109  79  45    27.667528  79.685428  6.490074  108.664640       banana
349     9  80  19    21.806196  18.570866  5.945466  125.097269  kidneybeans
654    17  58  20    28.066428  85.916255  6.429379   39.238310     mungbean
1335  108  22  46    26.176687  86.729520  6.121169   53.334850   watermelon
1356  118  21  51    24.429989  86.339048  6.678805   48.582418   watermelon
611    17  52  17    27.883529  86.451476  6.364967   44.644071     mungbean
803    11  74  17    21.363838  69.923759  6.633865   46.635286       lentil
216    50  56  76    20.995022  19.860130  7.966605   73.507340     chickpea
1484  120  16  51    27.999018  91.641931  6.547042   23.286182    muskmelon
1106   19  21  34    30.015926  53.192124  5.074273   97.728432        mango

In [53]:
# Showing unique crops (first)
unique_crops=crops_df.drop_duplicates(subset=['label'],keep='first')
print(unique_crops)

        N    P    K  temperature   humidity        ph    rainfall        label
0      90   42   43    20.879744  82.002744  6.502985  202.935536         rice
100    71   54   16    22.613600  63.690706  5.749914   87.759539        maize
200    40   72   77    17.024985  16.988612  7.485996   88.551231     chickpea
300    13   60   25    17.136928  20.595417  5.685972  128.256862  kidneybeans
400     3   72   24    36.512684  57.928872  6.031608  122.653969   pigeonpeas
500     3   49   18    27.910952  64.709306  3.692864   32.678919    mothbeans
600    19   55   20    27.433294  87.805077  7.185301   54.733676     mungbean
700    56   79   15    29.484400  63.199153  7.454532   71.890907    blackgram
800    32   76   15    28.051536  63.498022  7.604110   43.357954       lentil
900     2   24   38    24.559816  91.635362  5.922936  111.968462  pomegranate
1000   91   94   46    29.367924  76.249001  6.149934   92.828409       banana
1100    2   40   27    29.737700  47.548852  5.954627   90.095869        mango
1200   24  130  195    29.996772  81.541566  6.112306   67.125345       grapes
1300  119   25   51    26.473302  80.922544  6.283818   53.657426   watermelon
1400  115   17   55    27.578269  94.118782  6.776533   28.082532    muskmelon
1500   24  128  196    22.750888  90.694892  5.521467  110.431786        apple
1600   22   30   12    15.781442  92.510777  6.354007  119.035002       orange
1700   61   68   50    35.214628  91.497251  6.793245  243.074507       papaya
1800   18   30   29    26.762749  92.860569  6.420019  224.590366      coconut
1900  133   47   24    24.402289  79.197320  7.231325   90.802236       cotton
2000   89   47   38    25.524690  72.248508  6.002525  151.886997         jute
2100   91   21   26    26.333780  57.364700  7.261314  191.654941       coffee